/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServiziItRouteImport } from './routes/servizi-it'
import { Route as ServiziRouteImport } from './routes/servizi'
import { Route as RicercaInnovazioneRouteImport } from './routes/ricerca-innovazione'
import { Route as ProgettazioneFibraRouteImport } from './routes/progettazione-fibra'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ConsulenzaImpreseRouteImport } from './routes/consulenza-imprese'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziItRoute = ServiziItRouteImport.update({
  id: '/servizi-it',
  path: '/servizi-it',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziRoute = ServiziRouteImport.update({
  id: '/servizi',
  path: '/servizi',
  getParentRoute: () => rootRouteImport,
} as any)
const RicercaInnovazioneRoute = RicercaInnovazioneRouteImport.update({
  id: '/ricerca-innovazione',
  path: '/ricerca-innovazione',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgettazioneFibraRoute = ProgettazioneFibraRouteImport.update({
  id: '/progettazione-fibra',
  path: '/progettazione-fibra',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsulenzaImpreseRoute = ConsulenzaImpreseRouteImport.update({
  id: '/consulenza-imprese',
  path: '/consulenza-imprese',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/consulenza-imprese': typeof ConsulenzaImpreseRoute
  '/contatti': typeof ContattiRoute
  '/progettazione-fibra': typeof ProgettazioneFibraRoute
  '/ricerca-innovazione': typeof RicercaInnovazioneRoute
  '/servizi': typeof ServiziRoute
  '/servizi-it': typeof ServiziItRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/consulenza-imprese': typeof ConsulenzaImpreseRoute
  '/contatti': typeof ContattiRoute
  '/progettazione-fibra': typeof ProgettazioneFibraRoute
  '/ricerca-innovazione': typeof RicercaInnovazioneRoute
  '/servizi': typeof ServiziRoute
  '/servizi-it': typeof ServiziItRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/consulenza-imprese': typeof ConsulenzaImpreseRoute
  '/contatti': typeof ContattiRoute
  '/progettazione-fibra': typeof ProgettazioneFibraRoute
  '/ricerca-innovazione': typeof RicercaInnovazioneRoute
  '/servizi': typeof ServiziRoute
  '/servizi-it': typeof ServiziItRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chi-siamo'
    | '/consulenza-imprese'
    | '/contatti'
    | '/progettazione-fibra'
    | '/ricerca-innovazione'
    | '/servizi'
    | '/servizi-it'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chi-siamo'
    | '/consulenza-imprese'
    | '/contatti'
    | '/progettazione-fibra'
    | '/ricerca-innovazione'
    | '/servizi'
    | '/servizi-it'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/chi-siamo'
    | '/consulenza-imprese'
    | '/contatti'
    | '/progettazione-fibra'
    | '/ricerca-innovazione'
    | '/servizi'
    | '/servizi-it'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChiSiamoRoute: typeof ChiSiamoRoute
  ConsulenzaImpreseRoute: typeof ConsulenzaImpreseRoute
  ContattiRoute: typeof ContattiRoute
  ProgettazioneFibraRoute: typeof ProgettazioneFibraRoute
  RicercaInnovazioneRoute: typeof RicercaInnovazioneRoute
  ServiziRoute: typeof ServiziRoute
  ServiziItRoute: typeof ServiziItRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi-it': {
      id: '/servizi-it'
      path: '/servizi-it'
      fullPath: '/servizi-it'
      preLoaderRoute: typeof ServiziItRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi': {
      id: '/servizi'
      path: '/servizi'
      fullPath: '/servizi'
      preLoaderRoute: typeof ServiziRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ricerca-innovazione': {
      id: '/ricerca-innovazione'
      path: '/ricerca-innovazione'
      fullPath: '/ricerca-innovazione'
      preLoaderRoute: typeof RicercaInnovazioneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progettazione-fibra': {
      id: '/progettazione-fibra'
      path: '/progettazione-fibra'
      fullPath: '/progettazione-fibra'
      preLoaderRoute: typeof ProgettazioneFibraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consulenza-imprese': {
      id: '/consulenza-imprese'
      path: '/consulenza-imprese'
      fullPath: '/consulenza-imprese'
      preLoaderRoute: typeof ConsulenzaImpreseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChiSiamoRoute: ChiSiamoRoute,
  ConsulenzaImpreseRoute: ConsulenzaImpreseRoute,
  ContattiRoute: ContattiRoute,
  ProgettazioneFibraRoute: ProgettazioneFibraRoute,
  RicercaInnovazioneRoute: RicercaInnovazioneRoute,
  ServiziRoute: ServiziRoute,
  ServiziItRoute: ServiziItRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
