/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as ContattiRouteImport } from './routes/contatti'
import { Route as ChiSiamoRouteImport } from './routes/chi-siamo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiziIndexRouteImport } from './routes/servizi/index'
import { Route as ServiziItSoftwareRouteImport } from './routes/servizi/it-software'
import { Route as ServiziFibraMobileRouteImport } from './routes/servizi/fibra-mobile'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContattiRoute = ContattiRouteImport.update({
  id: '/contatti',
  path: '/contatti',
  getParentRoute: () => rootRouteImport,
} as any)
const ChiSiamoRoute = ChiSiamoRouteImport.update({
  id: '/chi-siamo',
  path: '/chi-siamo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziIndexRoute = ServiziIndexRouteImport.update({
  id: '/servizi/',
  path: '/servizi/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziItSoftwareRoute = ServiziItSoftwareRouteImport.update({
  id: '/servizi/it-software',
  path: '/servizi/it-software',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiziFibraMobileRoute = ServiziFibraMobileRouteImport.update({
  id: '/servizi/fibra-mobile',
  path: '/servizi/fibra-mobile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servizi/fibra-mobile': typeof ServiziFibraMobileRoute
  '/servizi/it-software': typeof ServiziItSoftwareRoute
  '/servizi/': typeof ServiziIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servizi/fibra-mobile': typeof ServiziFibraMobileRoute
  '/servizi/it-software': typeof ServiziItSoftwareRoute
  '/servizi': typeof ServiziIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chi-siamo': typeof ChiSiamoRoute
  '/contatti': typeof ContattiRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/servizi/fibra-mobile': typeof ServiziFibraMobileRoute
  '/servizi/it-software': typeof ServiziItSoftwareRoute
  '/servizi/': typeof ServiziIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/cookie-policy'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/servizi/fibra-mobile'
    | '/servizi/it-software'
    | '/servizi/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/cookie-policy'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/servizi/fibra-mobile'
    | '/servizi/it-software'
    | '/servizi'
  id:
    | '__root__'
    | '/'
    | '/chi-siamo'
    | '/contatti'
    | '/cookie-policy'
    | '/privacy-policy'
    | '/sitemap.xml'
    | '/servizi/fibra-mobile'
    | '/servizi/it-software'
    | '/servizi/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChiSiamoRoute: typeof ChiSiamoRoute
  ContattiRoute: typeof ContattiRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServiziFibraMobileRoute: typeof ServiziFibraMobileRoute
  ServiziItSoftwareRoute: typeof ServiziItSoftwareRoute
  ServiziIndexRoute: typeof ServiziIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatti': {
      id: '/contatti'
      path: '/contatti'
      fullPath: '/contatti'
      preLoaderRoute: typeof ContattiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chi-siamo': {
      id: '/chi-siamo'
      path: '/chi-siamo'
      fullPath: '/chi-siamo'
      preLoaderRoute: typeof ChiSiamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi/': {
      id: '/servizi/'
      path: '/servizi'
      fullPath: '/servizi/'
      preLoaderRoute: typeof ServiziIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi/it-software': {
      id: '/servizi/it-software'
      path: '/servizi/it-software'
      fullPath: '/servizi/it-software'
      preLoaderRoute: typeof ServiziItSoftwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servizi/fibra-mobile': {
      id: '/servizi/fibra-mobile'
      path: '/servizi/fibra-mobile'
      fullPath: '/servizi/fibra-mobile'
      preLoaderRoute: typeof ServiziFibraMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChiSiamoRoute: ChiSiamoRoute,
  ContattiRoute: ContattiRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServiziFibraMobileRoute: ServiziFibraMobileRoute,
  ServiziItSoftwareRoute: ServiziItSoftwareRoute,
  ServiziIndexRoute: ServiziIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
